import PDFDocument from 'pdfkit'

export interface CertificateParams {
  organisationName: string
  documentTitle: string
  documentNumber: string
  documentVersion: number
  revision: string
  effectiveDate: string
  userName: string
  userEmail: string
  employeeNumber?: string
  sectionName?: string
  signedAt: string
  signingMethod: string
  signingHash: string
  ipAddress: string
  assignmentId: string
}

export async function generateSigningCertificate(params: CertificateParams): Promise<Buffer> {
  const doc = new PDFDocument({ size: 'A4', margin: 50 })
  const chunks: Buffer[] = []

  doc.on('data', (chunk) => chunks.push(chunk))

  // Helper function to format dates
  const formatDate = (dateStr: string): string => {
    try {
      const date = new Date(dateStr)
      const pad = (n: number) => String(n).padStart(2, '0')
      const day = pad(date.getUTCDate())
      const month = date.toLocaleString('en-US', { month: 'short', timeZone: 'UTC' })
      const year = date.getUTCFullYear()
      const hours = pad(date.getUTCHours())
      const minutes = pad(date.getUTCMinutes())
      const seconds = pad(date.getUTCSeconds())
      return `${day} ${month} ${year} ${hours}:${minutes}:${seconds} UTC`
    } catch {
      return dateStr
    }
  }

  const colors = {
    navy: '#1B3A5C',
    blue: '#2E75B6',
    grey: '#718096',
    lightGrey: '#F7F9FC',
    darkGrey: '#4a5568',
    border: '#E2E8F0',
  }

  // Header
  doc.rect(0, 0, doc.page.width, 80).fill(colors.navy)
  doc.fontSize(18)
  doc.fillColor('white')
  doc.font('Helvetica-Bold')
  doc.text('READ & SIGN COMPLIANCE CERTIFICATE', 50, 18, { align: 'center', width: doc.page.width - 100 })

  doc.fontSize(10)
  doc.fillColor('#90B8D8')
  doc.font('Helvetica')
  doc.text(params.organisationName, 50, 48, { align: 'center', width: doc.page.width - 100 })

  // Divider line
  doc.moveTo(50, 90)
  doc.lineTo(doc.page.width - 50, 90)
  doc.strokeColor(colors.blue)
  doc.lineWidth(2)
  doc.stroke()

  let y = 110

  // Helper to draw a section
  const drawSection = (title: string, items: Array<[string, string]>) => {
    doc.fontSize(10)
    doc.fillColor(colors.navy)
    doc.font('Helvetica-Bold')
    doc.text(title.toUpperCase(), 50, y)
    y += 20

    doc.font('Helvetica')
    doc.fillColor(colors.darkGrey)

    // Draw alternating background rows
    let rowY = y
    let rowIndex = 0
    const lineHeight = 24

    for (const [key, value] of items) {
      // Alternating background
      if (rowIndex % 2 === 1) {
        doc.rect(50, rowY - 4, doc.page.width - 100, lineHeight).fill(colors.lightGrey)
        doc.fillColor(colors.darkGrey)
      }

      // Key-value pair
      doc.fontSize(9)
      doc.fillColor(colors.grey)
      doc.text(key, 60, rowY, { width: 150 })

      doc.fontSize(9)
      doc.fillColor(colors.darkGrey)
      doc.text(value, 220, rowY, { width: doc.page.width - 280 })

      rowY += lineHeight
      rowIndex++
    }

    y = rowY + 8
    return y
  }

  // Document Information
  y = drawSection('DOCUMENT INFORMATION', [
    ['Title', params.documentTitle],
    ['Document Number', params.documentNumber],
    ['Version', `v${params.documentVersion}, Revision ${params.revision}`],
    ['Effective Date', params.effectiveDate],
  ])

  y += 4

  // Acknowledgment Record
  y = drawSection('ACKNOWLEDGMENT RECORD', [
    ['Name', params.userName],
    ['Email', params.userEmail],
    ['Employee #', params.employeeNumber || '—'],
    ['Section', params.sectionName || '—'],
  ])

  y += 4

  // Signing Event
  y = drawSection('SIGNING EVENT', [
    ['Date & Time', formatDate(params.signedAt)],
    ['Signing Method', params.signingMethod],
    ['IP Address', params.ipAddress],
  ])

  y += 4

  // Cryptographic Verification
  y = drawSection('CRYPTOGRAPHIC VERIFICATION', [
    ['Assignment ID', params.assignmentId],
    ['Integrity Hash', params.signingHash],
    ['Algorithm', 'SHA-256'],
  ])

  // Footer
  y += 20
  doc.moveTo(50, y)
  doc.lineTo(doc.page.width - 50, y)
  doc.strokeColor(colors.border)
  doc.lineWidth(0.5)
  doc.stroke()

  y += 12
  doc.fontSize(9)
  doc.fillColor(colors.grey)
  doc.font('Helvetica-Oblique')
  const footerText =
    'This certificate is an authentic record generated by the Read and Sign platform. The integrity hash can be used to verify the authenticity of this signing event.'
  doc.text(footerText, 50, y, { width: doc.page.width - 100, align: 'left' })

  y += 40
  doc.fontSize(8)
  doc.font('Helvetica')
  const now = new Date()
  const generatedDate = `${String(now.getUTCDate()).padStart(2, '0')} ${now.toLocaleString('en-US', {
    month: 'short',
    timeZone: 'UTC',
  })} ${now.getUTCFullYear()} ${String(now.getUTCHours()).padStart(2, '0')}:${String(now.getUTCMinutes()).padStart(2, '0')}:${String(now.getUTCSeconds()).padStart(2, '0')} UTC`
  doc.text(`Generated: ${generatedDate}`, 50, y, { align: 'center', width: doc.page.width - 100 })

  // End PDF generation
  await new Promise<void>((resolve) => {
    doc.on('end', resolve)
    doc.end()
  })

  return Buffer.concat(chunks)
}
